name: Reusable workflow example

on:
  workflow_call:
    secrets:
      token:
        required: true


jobs:
  lint:
    name: Lint the Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.29
  test:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Unit tests.
        run: go test ./... -coverprofile=c.out

  release:
    name: Release a new version
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.token }}