name: Zengine Dev CD

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout the repo
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/zenginedev/tenants-rpc
          tags: |
            type=semver,pattern={{raw}},value=${{ steps.semver.outputs.VERSION }}
          labels: |
            org.opencontainers.image.title=Tenants gRPC Server
      - name: Build Binary
        run: CGO_ENABLED=0 GOOS=linux go build -mod=readonly -v -o ./bin/rpc ./cmd/rpc
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.6.1
        with:
          file: './build/docker/rpc/Dockerfile'
          context: './'
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}